backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"
local_backend: true

collections:
  - name: "main"
    label: "Главная страница"
    files:
      - name: "main"
        file: "data/data.json"
        label: "Главная"
        fields:
          - name: "main"
            label: "Главная"
            widget: "object"
            fields:
              - { name: "gif", label: "GIF-изображение", widget: "image", required: true }

  - name: "about"
    label: "Страница 'Об авторе'"
    files:
      - name: "about"
        file: "data/data.json"
        label: "Об авторе"
        fields:
          - name: "about"
            widget: "object"
            fields:
              - { name: "photo", label: "Фото автора", widget: "image", required: true }
              - { name: "title", label: "Заголовок", widget: "string" }
              - name: "text"
                label: "Текст"
                widget: "list"
                fields:
                  - { name: "paragraph", label: "Параграф", widget: "text" }

  # - name: "sound-art"
  #   label: "Саунд арт"
  #   files:
  #     - name: "sound-art"
  #       file: "data/sound.json"
  #       label: "Саунд арт"
  #       fields:
  #         - name: "sound-art"
  #           widget: "object"
  #           fields:
  #             - { name: "cover", label: "Обложка", widget: "image", required: true }
  #             - { name: "title", label: "Название трека", widget: "string", required: true }
  #             - { name: "event", label: "Мероприятие", widget: "string" }
  #             - { name: "year", label: "Год создания", widget: "string" }
  #             - { name: "description", label: "Описание композиции", widget: "text" }
