backend:
  name: git-gateway
  branch: master

media_folder: "src/images/main"
public_folder: "/static"

collections:
  - name: "main"
    label: "Main Screen"
    delete: false
    files:
      - label: "Main GIF"
        name: "main_gif"
        file: "data/main.json"
        fields:
          - { label: "GIF Image", name: "gif", widget: "image" }
