backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "main"
    label: "Главный экран"
    delete: false
    files:
      - label: "Главное изображение"
        file: "data/main.json"
        name: "main_gif"
        fields:
          - { name: "gif", label: "Изображение", widget: "image" }

  - name: "about"
    label: "Об авторе"
    delete: false
    create: true
    files:
      - label: "Контент"
        file: "data/main.json"
        name: "about"
        fields:
          - { name: "photo", label: "Фото", widget: "image" }
          - { name: "title", label: "Заголовок", widget: "text" }
          # - { name: "text", label: "Текст", widget: "list", fields: [{ name: paragraph, label: "Первый абзац", widget: "text" }]}
          - name: "text"
            label: "Текст"
            widget: "list"
            fields:
              - { name: "paragraph", label: "Абзац", widget: "string" }
