backend:
  name: git-gateway
  branch: master

media_folder: "static/images/main"
public_foldeer: "/images/main"

collections:
  - name: "main"
    label: "Main Screen"
    delete: false
    files:
      - label: "Main GIF"
        name: "main_gif"
        file: "content/main.json"
    fields:
      - { label: "GIF Image", name: "gif", widget: "image" }
